# Generated by Django 4.1.3 on 2022-11-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, verbose_name="Nombre"),
                ),
                (
                    "climate",
                    models.CharField(blank=True, max_length=200, verbose_name="Clima"),
                ),
                (
                    "diameter",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Diametro"
                    ),
                ),
                (
                    "population",
                    models.CharField(
                        blank=True,
                        default="Prueba",
                        max_length=20,
                        verbose_name="Población",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Planeta",
                "verbose_name_plural": "Planetas",
            },
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Título"),
                ),
                (
                    "episode_id",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Id Episodio"
                    ),
                ),
                (
                    "text_detail",
                    models.CharField(
                        blank=True, max_length=1200, verbose_name="Texto apertura"
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Director"
                    ),
                ),
                (
                    "producer",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Productor"
                    ),
                ),
                (
                    "release_date",
                    models.DateField(blank=True, verbose_name="Fecha de lanzamiento"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "planets",
                    models.ManyToManyField(to="app.planet", verbose_name="Panetas"),
                ),
            ],
            options={
                "verbose_name": "Película",
                "verbose_name_plural": "Películas",
            },
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=200, verbose_name="Nombre"),
                ),
                (
                    "gender",
                    models.CharField(blank=True, max_length=200, verbose_name="Género"),
                ),
                (
                    "height",
                    models.CharField(blank=True, max_length=3, verbose_name="Altura"),
                ),
                (
                    "mass",
                    models.CharField(blank=True, max_length=3, verbose_name="Peso"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "films",
                    models.ManyToManyField(to="app.film", verbose_name="Películas"),
                ),
            ],
            options={
                "verbose_name": "Personaje",
                "verbose_name_plural": "Personajes",
            },
        ),
    ]
