# Generated by Django 4.1.3 on 2022-11-18 14:50

from django.db import migrations
from app.models import Character, Film


def add_characters(apps, editor_schema):

    characters = [
        {
            "name": "Luke Skywalker",
            "height": "172",
            "mass": "77",
            "gender": "male",
            "film": "The Empire Strikes Back",
        },
        {
            "name": "C-3PO",
            "height": "167",
            "mass": "75",
            "gender": "n/a",
            "film": "The Empire Strikes Back",
        },
        {
            "name": "R2-D2",
            "height": "96",
            "mass": "32",
            "gender": "n/a",
            "film": "The Empire Strikes Back",
        },
        {
            "name": "Darth Vader",
            "height": "202",
            "mass": "136",
            "gender": "male",
            "film": "The Empire Strikes Back",
        },
        {
            "name": "Leia Organa",
            "height": "150",
            "mass": "49",
            "gender": "female",
            "film": "The Empire Strikes Back",
        },
        {
            "name": "Owen Lars",
            "height": "178",
            "mass": "120",
            "gender": "male",
            "film": "The Empire Strikes Back",
        },
        {
            "name": "Beru Whitesun lars",
            "height": "165",
            "mass": "75",
            "gender": "female",
            "film": "The Empire Strikes Back",
        },
        {
            "name": "R5-D4",
            "height": "97",
            "mass": "32",
            "gender": "n/a",
            "film": "Return of the Jedi",
        },
        {
            "name": "Biggs Darklighter",
            "height": "183",
            "mass": "84",
            "gender": "male",
            "film": "A New Hope",
        },
        {
            "name": "Obi-Wan Kenobi",
            "height": "182",
            "mass": "77",
            "gender": "male",
            "film": "A New Hope",
        },
        {
            "name": "Anakin Skywalker",
            "height": "188",
            "mass": "84",
            "gender": "male",
            "film": "Return of the Jedi",
        },
        {
            "name": "Wilhuff Tarkin",
            "height": "180",
            "mass": "100",
            "gender": "male",
            "film": "The Empire Strikes Back",
        },
        {
            "name": "Chewbacca",
            "height": "228",
            "mass": "112",
            "gender": "male",
            "film": "The Empire Strikes Back",
        },
        {
            "name": "Han Solo",
            "height": "180",
            "mass": "80",
            "gender": "male",
            "film": "A New Hope",
        },
    ]

    for character in characters:
        film_character = Film.objects.get(title=character["film"])
        new_character = Character(
            name=character["name"],
            gender=character["gender"],
            height=character["height"],
            mass=character["mass"],
        )
        new_character.save()
        new_character.films.add(film_character)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_auto_20221118_1449"),
    ]

    operations = [migrations.RunPython(add_characters)]
